#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

IMAGE=builder
FILE="vendor/docker/${IMAGE}.tar"

if [[ -e ${FILE} ]]; then
  docker load -i ${FILE}
else
  make .image-builder
  mkdir -p $(dirname ${FILE})
  docker save ${IMAGE} > ${FILE}
fi
