#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

IMAGE=$1
FILE="vendor/docker/${IMAGE}.tar"

if [[ -e ${FILE} ]]; then
  docker load -i ${FILE}
fi

make .image-${IMAGE}
mkdir -p $(dirname ${FILE})
docker save ${IMAGE} > ${FILE}
