#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

SRC=$1
DST=$2

REV=$(git rev-list -n 1 HEAD ${SRC});
STAMP=$(git show --pretty=format:%ai --abbrev-commit ${REV} | head -n 1);
touch -d "$STAMP" ${DST};
